=== ochaumont/skill-knowledge/src/main/resources/knowledge-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://knowledgeManagement/knowledge" 
	elementFormDefault="qualified"  
	xmlns="http://knowledgeManagement/knowledge">

    <xs:complexType name="consultant">	
	    <xs:sequence minOccurs="0" maxOccurs="unbounded">
	         <xs:element name="skill" type="skillRef"/>	      
	    </xs:sequence>	
	    <xs:attribute name="name" type="xs:string" use="required"/>	 
	    <xs:attribute name="firstname" type="xs:string" use="required"/>	       
	</xs:complexType>

	<xs:complexType name="skill">	
	    <xs:sequence minOccurs="0" maxOccurs="1">
	         <xs:element name="label" type="xs:string"/>
	         <xs:element name="description" type="xs:string"/>
	    </xs:sequence>	
	    <xs:attribute name="name" type="xs:string" use="required"/>	 
	    <xs:attribute name="type" type="xs:string" use="required"/>	       
	</xs:complexType>
	
	<xs:complexType name="skillRef">		    
	    <xs:attribute name="ref" type="xs:string" use="required"/>	
	    <xs:attribute name="level" type="xs:int" use="optional"/>	      
	</xs:complexType>
	
	<xs:complexType name="skillType">		    
	    <xs:attribute name="name" type="xs:string" use="required"/>	
	    <xs:attribute name="label" type="xs:string" use="required"/>	      
	</xs:complexType>
	
	<xs:complexType name="category">	
		 <xs:sequence>	   
		    <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="skill" type="skillRef" minOccurs="0" maxOccurs="unbounded"/>
		 </xs:sequence>
		 <xs:attribute name="name" type="xs:string" use="required"/>			
	</xs:complexType>

	<xs:complexType name="expertise">	
		<xs:sequence>
		  <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1"/>
	      <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>	     
	      <xs:element name="category" type="category" minOccurs="0" maxOccurs="unbounded"/>	    
	    </xs:sequence> 	 	
		<xs:attribute name="name" type="xs:string" use="required"/>								
	</xs:complexType>
	
	<xs:element name="knowledge">  
		<xs:complexType>	    	
	    	<xs:sequence>    	
	    	  <xs:element name="skillType" minOccurs="0" maxOccurs="unbounded" type="skillType"/>	
	    	  <xs:element name="skill" minOccurs="0" maxOccurs="unbounded" type="skill"/>	    						
	    	  <xs:element name="expertise" minOccurs="0" maxOccurs="unbounded" type="expertise"/>
	    	  <xs:element name="consultant" minOccurs="0" maxOccurs="unbounded" type="consultant"/>	    			    		
	    	</xs:sequence>	  
		</xs:complexType>	    	
    </xs:element>

</xs:schema>

=== ochaumont/skill-knowledge/src/main/resources/knowledgeBase-skillTypes.xml
<knowledge xmlns="http://knowledgeManagement/knowledge"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://knowledgeManagement/knowledge knowledge-1.0.xsd">
             
    <skillType name="knowledge"              label="Connaissance" />
    <skillType name="language"               label="langage"      />
    <skillType name="protocol"               label="Protocol" />
    <skillType name="application_server"     label="Serveurs d'application" />
    <skillType name="database_relationnelle" label="Base de données relationnelle" />
    <skillType name="database_nosql"         label="Base de données NoSQL" />
    <skillType name="framework"              label="Framework" />
    <skillType name="tools-mock"             label="Outils de Mock" />
    <skillType name="tools-unit-test"        label="Utilitaires pour tests unitaires" />
    <skillType name="tools-ihm-test"         label="Utilitaires pour tests d'IHL" />
    <skillType name="tools-perf-test"         label="Utilitaires pour tests de performance" />
    <skillType name="tools-analyse-test"      label="Utilitaires pour analyser une application" />
    <skillType name="tools-quality"          label="Utilitaires pour analyser la qualité du code" />
    <skillType name="tools-source-manager"   label="Utilitaires pour gérer les sources " />
       
</knowledge>

=== ochaumont/skill-knowledge/src/main/resources/knowledgeBase-consultants.xml
<knowledge xmlns="http://knowledgeManagement/knowledge"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://knowledgeManagement/knowledge knowledge-1.0.xsd">
     
     <consultant name="chaumont" firstname="olivier">          
		<skill ref="mvc"                    level="5"/> 
		<skill ref="java_se"                level="5"/>
		<skill ref="java_me"                level="1"/>
		<skill ref="java_ee"                level="5"/>
		<skill ref="java_swing"             level="2"/>
		<skill ref="java_fx"                level="0"/> 
		<skill ref="flex"                   level="1"/>   
		<skill ref="rmi"                    level="3"/>   
		<skill ref="ejb"                    level="4"/>   
		<skill ref="servlet"                level="5"/>   
		  		 
		<skill ref="database_sql"           level="3"/>   
		<skill ref="jndi"                   level="3"/>   
		<skill ref="jmx"                    level="2"/>   
		<skill ref="pool"                   level="5"/>   
		<skill ref="websphere"              level="3"/>   
		<skill ref="weblogic"               level="3"/>   
		<skill ref="jboss"                  level="2"/>   
		<skill ref="glassfish"              level="2"/>  
		<skill ref="tomcat"                 level="3"/>   
		<skill ref="acid"                   level="5"/>   
		
		<skill ref="normalisation_database" level="4"/>   		
		<skill ref="jpa"                    level="3"/>   
		<skill ref="jdbc"                   level="4"/>   
		<skill ref="nosql"                  level="1"/>   
		<skill ref="sql"                    level="3"/>   
		<skill ref="pl_sql"                 level="1"/>   
		<skill ref="oracle"                 level="3"/>   
		<skill ref="junit"                  level="5"/>   
		<skill ref="selenium"               level="4"/>  
     </consultant>
 
         
     
</knowledge>

=== ochaumont/skill-knowledge/src/main/resources/knowledgeBase-expertises.xml
<knowledge xmlns="http://knowledgeManagement/knowledge"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://knowledgeManagement/knowledge knowledge-1.0.xsd">

              
    <expertise name="rda">
         <label>RDA (Rich Desktop Application)</label>  
         <description>Conception d'application lourdes déployées en local.</description>
         
         <category name="knowledge">
              <label>Connaissance</label>
              <description></description>              
              <skill ref="mvc"/>              
         </category>          
 
         <category name="language">
              <label>Langage</label>
              <description></description>              
			  <skill ref="java_se"/>  
			  <skill ref="java_swing"/>      
			  <skill ref="flex"/> 
	     </category> 
	     
         <category name="protocol">
              <label>Protocole</label>
              <description></description>              
			  <skill ref="rmi"/>  			
	     </category>                 
        
    </expertise>
   
    <expertise name="application-server">
         <label>Serveurs d'applications</label>  
         <description>Configuration des serveurs d'application.</description>
         
         <category name="knowledge">
              <label>Connaissance</label>
              <description></description>              
              <skill ref="ejb"/>
              <skill ref="servlet"/>
              <skill ref="database_sql"/>
              <skill ref="jndi"/>
              <skill ref="jmx"/>
              <skill ref="pool"/>                       
         </category>          
 
         <category name="application-server">
              <label>Serveurs d'application</label>
              <description></description>              
			  <skill ref="websphere"/>  
			  <skill ref="weblogic"/>      
			  <skill ref="jboss"/> 
			  <skill ref="glassfish"/>
			  <skill ref="tomcat"/>
	     </category> 
        
    </expertise>    
</knowledge>

=== ochaumont/skill-knowledge/src/main/resources/knowledgeBase.xml
<knowledge xmlns="http://knowledgeManagement/knowledge"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://knowledgeManagement/knowledge knowledge-1.0.xsd">

     
     <skill name="skill_1" type="type1">
          <label>label 1</label>
          <description>description 1</description>            
     </skill>
         
    <expertise name="expertise_1">
         <label>label 1</label>  
         <description>description 2</description>
         <category name="category_1">
              <label>label 1</label>
              <description>description 1</description>              
              <skill ref="skill_1"/>              
           </category>          
        
    </expertise>
   
    
</knowledge>
